import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
import { TanstackProvider } from './_providers';
import './globals.css';

const poppins = Poppins({
	variable: '--font-poppins',
	subsets: ['latin'],
	weight: ['300', '500', '700'],
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html
			lang='es'
			suppressHydrationWarning>
			<body className={`${poppins.variable} antialiased font-poppins`}>
				<TanstackProvider>{children}</TanstackProvider>
			</body>
		</html>
	);
}
